del jules-verne.lot
del jules-verne.lof
del jules-verne.toc
del jules-verne.gls.*
del jules-verne.losa.*
del jules-verne.idx
del jules-verne.ind
del jules-verne.ilg
del jules-verne.lol
del jules-verne.out
del jules-verne.bbl
del jules-verne.blg
del jules-verne.brf
del jules-verne.tpt
del *.aux
del *.log
del *.bak
del *~
